# Generated by Django 5.2.1 on 2025-06-01 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentScenario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('img_path', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('priority', models.CharField(default='100', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assessment_date', models.DateField()),
                ('result_summary', models.TextField()),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('as_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessmentscenario')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contant_info', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.parent')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_order', models.CharField(default='100', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('as_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessmentscenario')),
            ],
        ),
        migrations.CreateModel(
            name='RecordingStep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('img_path', models.CharField(max_length=255)),
                ('expected_duration', models.DurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('as_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessmentscenario')),
            ],
        ),
        migrations.CreateModel(
            name='PatientFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], max_length=50)),
                ('duration', models.DurationField()),
                ('model_name', models.CharField(max_length=255)),
                ('model_response', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessment')),
                ('step_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.recordingstep')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('model_name', models.CharField(max_length=255)),
                ('model_response', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessment')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.question')),
            ],
        ),
    ]
