# Generated by Django 5.2.1 on 2025-07-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultant',
            old_name='specialization',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='user',
        ),
        migrations.AddField(
            model_name='consultant',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='areaOfFocus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultant',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='consultant',
            name='reviews',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='specialty',
            field=models.CharField(default='ss', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultant',
            name='workingTime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
